---
language: ruby

script: bundle exec rake

sudo: false

rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - rbx
  - jruby-9

matrix:
  exclude:
    - rvm: 2.2
      os: osx
    - rvm: jruby-9
      os: osx

notifications:
  email:
    recipients:
      - yorickpeterse@gmail.com
    on_success: change
    on_failure: change

cache: bundler

branches:
  only:
    - master

os:
  - linux
  - osx
