---
version: "{build}"

install:
  # Binary taken from http://w858rkbfg.homepage.t-online.de/index.php/software/ragel-windows/,
  # rehosted on AWS so it doesn't randomly vanish.
  - appveyor DownloadFile http://downloads.yorickpeterse.com/files/ragel-68-visualstudio2012.7z -FileName C:\ragel.7z
  - 7z e C:\ragel.7z -oC:\ragel -y > nul
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - SET PATH=C:\ragel;%PATH%
  - ruby --version
  - gem --version
  - gem install --local C:\Ruby%ruby_version%\lib\ruby\gems\%abi_version%\cache\bundler-1.9.0.gem --quiet --no-ri --no-rdoc
  - bundle install --retry 3

build: off

test_script:
  - rake

environment:
  matrix:
    -
      ruby_version: "193"
      abi_version: "1.9.1"
    -
      ruby_version: "200"
      abi_version: "2.0.0"
    -
      ruby_version: "21"
      abi_version: "2.1.0"
    -
      ruby_version: "21-x64"
      abi_version: "2.1.0"
    -
      ruby_version: "22"
      abi_version: "2.2.0"
    -
      ruby_version: "22-x64"
      abi_version: "2.2.0"

skip_tags: true

notifications:
  -
    provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
